CREATE EXTERNAL TABLE IF NOT EXISTS json_import_new (
  posting_id STRING,
  additional_source_id STRING COMMENT 'from deserializer',
  additional_source_name STRING COMMENT 'from deserializer',
  additional_tender_url STRING COMMENT 'from deserializer',
  attachments ARRAY<STRUCT<
    external_url: STRING,
    file_description: STRING,
    file_name: STRING,
    file_size: DOUBLE,
    file_type: STRING,
    id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  bidding_response_method STRING COMMENT 'from deserializer',
  category STRING COMMENT 'from deserializer',
  class_at_source STRING COMMENT 'from deserializer',
  class_codes_at_source STRING COMMENT 'from deserializer',
  class_title_at_source STRING COMMENT 'from deserializer',
  completed_steps STRING COMMENT 'from deserializer',
  contract_duration STRING COMMENT 'from deserializer',
  contract_type_actual STRING COMMENT 'from deserializer',
  cpv_at_source STRING COMMENT 'from deserializer',
  cpvs ARRAY<STRUCT<
    cpv_code: STRING,
    id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  crawled_at STRING COMMENT 'from deserializer',
  currency STRING COMMENT 'from deserializer',
  custom_tags ARRAY<STRUCT<
    tender_custom_tag_company_id: STRING,
    tender_custom_tag_description: STRING,
    tender_custom_tag_value: STRING,
    custom_tags_id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  customer_details ARRAY<STRUCT<
    contact_person: STRING,
    customer_main_activity: STRING,
    customer_nuts: STRING,
    org_address: STRING,
    org_city: STRING,
    org_country: STRING,
    org_description: STRING,
    org_email: STRING,
    org_fax: STRING,
    org_language: STRING,
    org_name: STRING,
    org_parent_id: INT,
    org_phone: STRING,
    org_state: STRING,
    org_type: INT,
    org_website: STRING,
    postal_code: STRING,
    type_of_authority_code: STRING,
    org_id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  dispatch_date STRING COMMENT 'from deserializer',
  document_cost DOUBLE COMMENT 'from deserializer',
  document_fee STRING COMMENT 'from deserializer',
  document_opening_time STRING COMMENT 'from deserializer',
  document_purchase_end_time STRING COMMENT 'from deserializer',
  document_purchase_start_time STRING COMMENT 'from deserializer',
  document_type_description STRING COMMENT 'from deserializer',
  earnest_money_deposit STRING COMMENT 'from deserializer',
  eligibility STRING COMMENT 'from deserializer',
  est_amount DOUBLE COMMENT 'from deserializer',
  funding_agencies ARRAY<STRUCT<
    funding_agency: INT,
    id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  grossbudgeteuro DOUBLE COMMENT 'from deserializer',
  grossbudgetlc DOUBLE COMMENT 'from deserializer',
  identifier STRING COMMENT 'from deserializer',
  is_deadline_assumed BOOLEAN COMMENT 'from deserializer',
  is_lot_default BOOLEAN COMMENT 'from deserializer',
  is_publish_assumed BOOLEAN COMMENT 'from deserializer',
  is_publish_on_gec BOOLEAN COMMENT 'from deserializer',
  local_description STRING COMMENT 'from deserializer',
  local_title STRING COMMENT 'from deserializer',
  lot_details ARRAY<STRUCT<
    award_details: ARRAY<STRUCT<
      address: STRING,
      award_date: STRING,
      award_quantity: DOUBLE,
      bid_recieved: STRING,
      bidder_country: STRING,
      bidder_name: STRING,
      contract_duration: STRING,
      final_estimated_value: DOUBLE,
      grossawardvalueeuro: DOUBLE,
      grossawardvaluelc: DOUBLE,
      initial_estimated_value: DOUBLE,
      netawardvalueeuro: DOUBLE,
      netawardvaluelc: DOUBLE,
      notes: STRING,
      winner_group_name: STRING,
      id: STRING,
      lot_id: STRING,
      posting_id: STRING
    >>,
    contract_duration: STRING,
    contract_end_date: STRING,
    contract_number: STRING,
    contract_start_date: STRING,
    contract_type: STRING,
    lot_actual_number: STRING,
    lot_award_date: STRING,
    lot_cancellation_date: STRING,
    lot_class_codes_at_source: STRING,
    lot_contract_type_actual: STRING,
    lot_cpv_at_source: STRING,
    lot_cpvs: ARRAY<STRUCT<
      lot_id: STRING,
      lot_cpv_code: STRING,
      id: STRING,
      posting_id: STRING
    >>,
    lot_criteria: ARRAY<STRUCT<
      lot_id: STRING,
      lot_criteria_title: STRING,
      lot_criteria_weight: INT,
      lot_is_price_related: BOOLEAN,
      lot_criteria_id: STRING,
      posting_id: STRING
    >>,
    lot_description: STRING,
    lot_description_english: STRING,
    lot_grossbudget: DOUBLE,
    lot_grossbudget_lc: DOUBLE,
    lot_is_canceled: BOOLEAN,
    lot_max_quantity: DOUBLE,
    lot_min_quantity: DOUBLE,
    lot_netbudget: DOUBLE,
    lot_netbudget_lc: DOUBLE,
    lot_number: INT,
    lot_nuts: STRING,
    lot_quantity: DOUBLE,
    lot_quantity_uom: STRING,
    lot_title: STRING,
    lot_title_english: STRING,
    lot_vat: DOUBLE,
    lot_grossbudgeteuro: DOUBLE,
    lot_grossbudgetlc: DOUBLE,
    lot_id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  main_language STRING COMMENT 'from deserializer',
  netbudgeteuro DOUBLE COMMENT 'from deserializer',
  netbudgetlc DOUBLE COMMENT 'from deserializer',
  notice_contract_type STRING COMMENT 'from deserializer',
  notice_deadline STRING COMMENT 'from deserializer',
  notice_no STRING COMMENT 'from deserializer',
  notice_summary_english STRING COMMENT 'from deserializer',
  notice_text STRING COMMENT 'from deserializer',
  notice_title STRING COMMENT 'from deserializer',
  notice_type INT COMMENT 'from deserializer',
  notice_url STRING COMMENT 'from deserializer',
  performance_country ARRAY<STRUCT<
    performance_country: STRING,
    id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  performance_state ARRAY<STRUCT<
    performance_state: STRING,
    id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  pre_bid_meeting_date STRING COMMENT 'from deserializer',
  procurement_method INT COMMENT 'from deserializer',
  project_name STRING COMMENT 'from deserializer',
  publish_date STRING COMMENT 'from deserializer',
  related_tender_id STRING COMMENT 'from deserializer',
  source_of_funds STRING COMMENT 'from deserializer',
  tender_award_date STRING COMMENT 'from deserializer',
  tender_cancellation_date STRING COMMENT 'from deserializer',
  tender_contract_end_date STRING COMMENT 'from deserializer',
  tender_contract_number STRING COMMENT 'from deserializer',
  tender_contract_start_date STRING COMMENT 'from deserializer',
  tender_criteria ARRAY<STRUCT<
    tender_criteria_title: STRING,
    tender_criteria_weight: INT,
    tender_is_price_related: BOOLEAN,
    tender_criteria_id: STRING,
    posting_id: STRING
  >> COMMENT 'from deserializer',
  tender_id STRING COMMENT 'from deserializer',
  tender_is_canceled BOOLEAN COMMENT 'from deserializer',
  tender_max_quantity DOUBLE COMMENT 'from deserializer',
  tender_min_quantity DOUBLE COMMENT 'from deserializer',
  tender_quantity STRING COMMENT 'from deserializer',
  tender_quantity_uom STRING COMMENT 'from deserializer',
  type_of_procedure STRING COMMENT 'from deserializer',
  type_of_procedure_actual STRING COMMENT 'from deserializer',
  vat DOUBLE COMMENT 'from deserializer',
  script_name STRING)
PARTITIONED BY ( 

  `year` int COMMENT '', 
  `month` int COMMENT '', 
  `day` int COMMENT '',
  `country` STRING COMMENT ''
  )
ROW FORMAT SERDE 
  'org.openx.data.jsonserde.JsonSerDe' 
WITH SERDEPROPERTIES ( 
  'case.insensitive'='TRUE', 
  'dots.in.keys'='FALSE', 
  'ignore.malformed.json'='FALSE', 
  'mapping'='TRUE') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://gec-script-executions/json_import_new'
TBLPROPERTIES (
  'classification'='json', 
  'projection.country.type'='enum', 
  'projection.country.values'='do,lt,lu,mo,tl,ec,eg,sv,gq,er,mg,mw,my,mv,ee,et,fk,fo,fj,fi,fr,gf,bl,mf,vc,ml,mt,im,mh,mq,mr,mu,yt,pf,tf,ga,gm,ge,de,gh,gi,gr,gl,gd,gp,gu,gt,gg,gn,sn,rs,sc,sl,sg,sx,sk,si,ws,sm,st,sa,mx,fm,md,mc,mn,me,ms,ma,mz,mm,nr,np,nl,nc,nz,sb,so,za,gs,kr,ss,es,lk,sd,sr,sj,sz,se,ch,sy,tw,gw,gy,ht,hm,hn,hk,hu,is,in,id,ir,iq,ie,il,it,jm,jp,je,jo,kz,ke,ki,kw,kg,la,lv,lb,ls,lr,ly,li,ni,ne,ng,nu,nf,kp,mk,mp,no,om,pk,pw,ps,pa,pg,py,pe,ph,pn,pl,pt,pr,qa,re,ro,ru,rw,sh,kn,lc,pm,tj,tz,th,bs,tg,tk,to,tt,tn,tr,tm,tc,tv,ug,ua,ae,gb,us,um,uy,uz,vu,va,ve,vn,vg,vi,wf,eh,ye,zm,zw,kv,af,ax,al,dz,as,ad,ao,ai,aq,ag,ar,am,aw,bg,bf,bi,kh,cm,au,at,az,bh,bd,bb,by,be,bz,bj,bm,bt,bo,bq,ba,bw,bv,br,io,bn,ca,cv,ky,cf,td,cl,cn,cx,cc,co,km,cg,ck,cr,ci,hr,cu,cw,cy,cz,cd,dk,dj,dm', 
  'projection.day.digits'='2', 
  'projection.day.range'='1,31', 
  'projection.day.type'='integer', 
  'projection.enabled'='true', 
  'projection.month.digits'='2', 
  'projection.month.range'='1,12', 
  'projection.month.type'='integer', 
  'projection.year.range'='2021,2030', 
  'projection.year.type'='integer', 
  'transient_lastDdlTime'='1712054379')